### ISSUE TITLE
Ficha do Aluno "Erro no preenchimento do formulário"

### ISSUE THREAD

**Issue by Silvio553** [portabilis/ieducar#963]
Instalei o i-educar, mas ao solicitar Ficha do aluno, ao clicar no nome do aluno. Qualquer aluno aparece o mesmo problema "Erro no preenchimento do formulário" - Não Existe informação disponível.

Uso ubuntu 22.04
Navegador: Mozila Firefox

**Comment by edineivaldameri** [comment]
@Silvio553 por gentiliza forneça mais detalhes, print's das telas e do erro para podemos visualizar e simular o cenário do erro.

**Comment by Silvio553** [comment]
Veja o print
![Erro de Boletim](https://github.com/user-attachments/assets/91b2063d-5205-4aab-862c-61885d09bff2)

**Comment by edineivaldameri** [comment]
@Silvio553 essa tela não mostra o erro.
Consegue encaminhar os log's de erro do laravel e do postgres para que possamos auxiliar.

**Comment by edineivaldameri** [comment]
@Silvio553 verifique se esse tópico da comunidade ajuda você resolver seu problema com a Ficha do Aluno:
https://forum.ieducar.org/t/resolvido-ficha-do-aluno-erro-cad01/2490

**Comment by Silvio553** [comment]
São topicos diferentes veja o print completo.
![Erro no preenchimento do formulario](https://github.com/user-attachments/assets/0ad34fd1-bd05-4420-96b6-7ab360991ca8)

**Comment by Silvio553** [comment]
Abri o Laravel.log e peguei as últimas dez linhas.
#57 /var/www/ieducar/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\ChangeAppName->handle()
#58 /var/www/ieducar/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#59 /var/www/ieducar/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#60 /var/www/ieducar/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#61 /var/www/ieducar/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#62 /var/www/ieducar/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#63 /var/www/ieducar/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#64 /var/www/ieducar/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#65 /var/www/ieducar/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#66 /var/www/ieducar/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#67 /var/www/ieducar/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#68 /var/www/ieducar/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#69 /var/www/ieducar/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle()
#70 /var/www/ieducar/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#71 /var/www/ieducar/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()
#72 /var/www/ieducar/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#73 /var/www/ieducar/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then()
#74 /var/www/ieducar/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#75 /var/www/ieducar/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()
#76 {main}
"}

**Comment by edineivaldameri** [comment]
@Silvio553 nem sempre o erro está nas últimas 10 linhas.
O log do laravel sempre começa do topo (local mais específico) para baixo, (local menos específico) nesse caso as linhas que você trouxe, monstra apenas a cascata do fluxo do Laravel, do início do Kernel aos Middlewares, algo extremamente genérico e que não permite visualizar o erro real.

Segundo ponto, você trouxe um possível problema de relatório, mas esse é o repositório principal do i-educar, dúvidas sobre relatórios devemos centralizar no pacote de relatórios: https://github.com/portabilis/i-educar-reports-package.

Acredito que nesses casos o melhor cenário é fazer um .gif desde o preenchimento do formulário até o erro acontecer, e também olhar os erros no `log` do `postgres`, pois se o erro for na query do relatório lá ficará mais evidente.

**Comment by edersoares** [comment]
Um novo pacote de relatórios será liberado em breve e unificará todos os relatórios do i-Educar.
